# Generated by Django 4.2.16 on 2026-03-31 01:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Имя кота')),
                ('color', models.CharField(choices=[('black', 'Черный'), ('white', 'Белый'), ('orange', 'Рыжий'), ('gray', 'Серый'), ('mixed', 'Смешанный')], max_length=16, verbose_name='Окрас')),
                ('birth_year', models.PositiveIntegerField(verbose_name='Год рождения')),
                ('image', models.ImageField(blank=True, null=True, upload_to='cats/images/', verbose_name='Фото')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cats', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Кот',
                'verbose_name_plural': 'Коты',
                'ordering': ['name'],
            },
        ),
    ]
